name: TeXLive

on:
  workflow_dispatch:
  schedule:
    # 每月3号的0点执行 (北京时间+8)
    - cron: "0 0 3 * *"
  push:
    branches: [main]
    paths:
      - "texlive-en/Dockerfile.en"
      - "texlive-en/texlive.profile"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Podman Login
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: hankyproject
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          podman build --file ./texlive-en/Dockerfile.en --tag ghcr.io/hankyproject/texlive:latest ./texlive-en
          podman push ghcr.io/hankyproject/texlive:latest
